version: "3.9"
services:
  pdt-dev05:
    build: .
    image: "pdt-dev05:latest"
    container_name: pdt-dev05
    # restart: always
    restart: no
    command: ['tail', '-f', '/dev/null']
    network_mode: "host"
    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
      - LC_ALL=UTF-8
    volumes:
      - ../:/workspace
